# Generated by Django 4.0 on 2024-02-09 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='random_order',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
