# Generated by Django 4.0 on 2024-02-10 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_random_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('DocumentClassification', 'Document Classification'), ('SequenceLabeling', 'Sequence Labeling'), ('IntentDetectionAndSlotFilling', 'Intent Detection And Slot Filling'), ('ImageClassification', 'Image Classification'), ('BoundingBox', 'Bounding Box'), ('Seq2seq', 'Seq2Seq')], max_length=30),
        ),
    ]
