# Generated by Django 4.0 on 2024-02-06 20:23

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('label_types', '0002_initial'),
        ('labels', '0001_initial'),
        ('examples', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textlabel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='span',
            name='example',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spans', to='examples.example'),
        ),
        migrations.AddField(
            model_name='span',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='label_types.spantype'),
        ),
        migrations.AddField(
            model_name='span',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='segmentation',
            name='example',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segmentations', to='examples.example'),
        ),
        migrations.AddField(
            model_name='segmentation',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='label_types.categorytype'),
        ),
        migrations.AddField(
            model_name='segmentation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='relation',
            name='example',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='examples.example'),
        ),
        migrations.AddField(
            model_name='relation',
            name='from_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_relations', to='labels.span'),
        ),
        migrations.AddField(
            model_name='relation',
            name='to_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_relations', to='labels.span'),
        ),
        migrations.AddField(
            model_name='relation',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='label_types.relationtype'),
        ),
        migrations.AddField(
            model_name='relation',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='category',
            name='example',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='examples.example'),
        ),
        migrations.AddField(
            model_name='category',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='label_types.categorytype'),
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AddField(
            model_name='boundingbox',
            name='example',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bboxes', to='examples.example'),
        ),
        migrations.AddField(
            model_name='boundingbox',
            name='label',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='label_types.categorytype'),
        ),
        migrations.AddField(
            model_name='boundingbox',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
        migrations.AlterUniqueTogether(
            name='textlabel',
            unique_together={('example', 'user', 'text')},
        ),
        migrations.AddConstraint(
            model_name='span',
            constraint=models.CheckConstraint(check=models.Q(('start_offset__gte', 0)), name='startOffset >= 0'),
        ),
        migrations.AddConstraint(
            model_name='span',
            constraint=models.CheckConstraint(check=models.Q(('end_offset__gte', 0)), name='endOffset >= 0'),
        ),
        migrations.AddConstraint(
            model_name='span',
            constraint=models.CheckConstraint(check=models.Q(('start_offset__lt', django.db.models.expressions.F('end_offset'))), name='start < end'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('example', 'user', 'label')},
        ),
        migrations.AddConstraint(
            model_name='boundingbox',
            constraint=models.CheckConstraint(check=models.Q(('x__gte', 0)), name='x >= 0'),
        ),
        migrations.AddConstraint(
            model_name='boundingbox',
            constraint=models.CheckConstraint(check=models.Q(('y__gte', 0)), name='y >= 0'),
        ),
        migrations.AddConstraint(
            model_name='boundingbox',
            constraint=models.CheckConstraint(check=models.Q(('width__gte', 0)), name='width >= 0'),
        ),
        migrations.AddConstraint(
            model_name='boundingbox',
            constraint=models.CheckConstraint(check=models.Q(('height__gte', 0)), name='height >= 0'),
        ),
    ]
