# Generated by Django 4.0 on 2024-07-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='span',
            name='annotated_by',
            field=models.TextField(default='human', null=True),
        ),
    ]
