# Generated by Django 4.0 on 2024-08-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_span_annotated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='annotated_by',
            field=models.TextField(default='human', null=True),
        ),
    ]
