# Generated by Django 4.0 on 2024-09-04 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0004_category_annotated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='span',
            name='word',
            field=models.TextField(default='def'),
            preserve_default=False,
        ),
    ]
