# Generated by Django 4.0 on 2024-02-06 20:23

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examples', '0001_initial'),
        ('labels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportedBoundingBox',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('labels.boundingbox',),
        ),
        migrations.CreateModel(
            name='ExportedCategory',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('labels.category',),
        ),
        migrations.CreateModel(
            name='ExportedComment',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('examples.comment',),
        ),
        migrations.CreateModel(
            name='ExportedExample',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('examples.example',),
        ),
        migrations.CreateModel(
            name='ExportedRelation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('labels.relation',),
        ),
        migrations.CreateModel(
            name='ExportedSegmentation',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('labels.segmentation',),
        ),
        migrations.CreateModel(
            name='ExportedSpan',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('labels.span',),
        ),
        migrations.CreateModel(
            name='ExportedText',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('labels.textlabel',),
        ),
    ]
