# Generated by Django 4.0 on 2024-02-06 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('label_types', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spantype',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='relationtype',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='categorytype',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddConstraint(
            model_name='spantype',
            constraint=models.UniqueConstraint(fields=('project', 'text'), name='label_types_spantype_is_unique'),
        ),
        migrations.AddConstraint(
            model_name='relationtype',
            constraint=models.UniqueConstraint(fields=('project', 'text'), name='label_types_relationtype_is_unique'),
        ),
        migrations.AddConstraint(
            model_name='categorytype',
            constraint=models.UniqueConstraint(fields=('project', 'text'), name='label_types_categorytype_is_unique'),
        ),
    ]
